include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude: [
      lib/**.g.dart,
    ] #예외처리

  ## ignore(무시)
  ## info(정보)
  ## warning(경고)
  ## error(오류)

  errors:
    dead_code: warning
    avoid_print: warning
    todo: info

linter:
  rules:
    avoid_print: false
    depend_on_referenced_packages: false
    unnecessary_this: false
